description:  ${spring.application.description}
title:  ${spring.application.name}
version:  ${spring.application.version}

info:
  app:
    id: ${spring.application.id}
    name: ${spring.application.name}
    version: ${spring.application.version}

server:
  port: 17000

app:
  datasource:
    jdbc-url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool-size: 1000

spring:
  application:
    description: Lostboyz user service
    id: lostboyz-user-service
    name: lostboyz-user-service
    version: 0.0.1-SNAPSHOT
  output:
    ansi:
      enabled: detect
  flyway:
    baseline-on-migrate: true

logging:
  file:
    name: logs/lostboyz-user-service.log
  level:
    root: ERROR